# Generated by Django 4.2.6 on 2023-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_cliente_producto_alter_task_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('subtitulo', models.CharField(blank=True, max_length=50)),
                ('cuerpo', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField(blank=True)),
            ],
        ),
    ]
